### PR TITLE
Remove www from link

### PR DESCRIPTION
**Pull request by ablwr**
For `Reasons`, the www. causes the URL to return a server error. Removing it takes you to the content!

### CODE REVIEW

**Review by retokromer — APPROVED** [review]
Good catch, thank you!

**Comment by retokromer** [comment]
I cannot do it.

**Comment by ablwr** [comment]
@kgrons or @kfrn ? :innocent: I also can't tag you as reviewers.

**Comment by kgrons** [comment]
@ablwr thanks for the tag, I no longer have my admin access to this repo but will follow up with @dericed & merge this PR when we fix the permissions issue. Thank you for flagging & @retokromer for the approval.

**Pull request merged**
